### ISSUE TITLE
WoW ! Thank you . this is just what i was looking for

### ISSUE THREAD

**Issue by luismasg** [miyako/4d-plugin-jwt#1]
Great work . 

I'll kick the tires on it  a little to test it.
I'm really looking forward to collaborate on this
⭐️

**Comment by luismasg** [comment]
I'd loved to help write up the installation guide.
I would assume i just drop it in to the components folder just like VC_Framework ?

**Comment by miyako** [comment]
all plugins are installed in the same manner.
https://doc.4d.com/4Dv17R4/4D/17-R4/Installing-plugins-or-components.300-4085753.en.html

quite similar to components:
https://doc.4d.com/4Dv17R4/4D/17-R4/Overview.300-4085682.en.html

the main difference is the language used (C or 4D)

**Comment by luismasg** [comment]
Awesome,  I'll take it for a spin tomorrow, we're running on v16.

**Comment by luismasg** [comment]
Neat.
I was able to sign a token and verify it on jwt.io
but not  the othe way around. I created the token on the jwt.io and paste it in 4d along with the secret.
I _think_ I'm doing it right,
did I mess up ? 


![image](https://user-images.githubusercontent.com/12954857/59798821-a2807780-92a8-11e9-9e44-e1d33ec54e79.png)


```
$token:="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoiMTUxNjIzOTAyMiJ9.NTghxvd6D0DCZNZxlLf9U1wSJHxsA-m17OAOwcKKgzA"

$result:=JWT Verify ($token;"your-256-bit-secret")  // => 0
```

**Comment by miyako** [comment]
honestly I haven't thoroughly tested the "verify" command since we didn't need it for our project.

you can find my messy code in

https://github.com/miyako/4d-plugin-jwt/blob/master/4DPlugin.cpp
